# Site settings
lang: ru
title: vl.maksime GitHub Блог
description: >-
  Зачем мне нужен этот блог, пока не знаю...
  Раз завел, пусть будет.
github_username:  vlmaksime

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-redirect-from