# Site settings
title: Страница vl.maksime на GitHub
description: Мой небольшой блог, работающий на GitHub Pages
author: Владимир Максименко
email: vl.maksime@gmail.com
github_username: vlmaksime

baseurl: ""
url: "https://vlmaksime.github.io"

google_analytics: UA-131785381-1
allowsearch: false

enableTags: false
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-gist

remote_theme: "vlmaksime/material-jekyll-theme"
